travis:
  secure:
    BINSTAR_TOKEN: OviGOJeqCeKEu27oiyX18b44Mq1Q/zKZP8DjAuKUYV/dK6YPqG4yW59s0nnkmxqfpUmG/BWfnoEQV9J9DLaI6BoN8h3uL0/zsBQvWq60bl8MWLkBkct9Nn5GVxkxn/SpRIpf07CoIG78y29a9ZKNu7DOnKegL5EIu+3fl+YB87rSr0+9dmCjMBbz2B0mQU/DQTiXAilRJDGwid7XqzXfsx+GpZUihutF9qOMWOnJPR+KqNwKRfRh2rmaJ0lpcrVo/yBLOLrJfomoNziJYEfxtztflwrNPUHlgWblqofT8o8XOpFiyRLCVItxMve+RHvQjRrMWFChWARvdXAqJqVltfugB73e4EXPl4nwck4XZiERaaqck8wQwj/YSy1v6+xVTolk5v+T7vV2gr31aeyK+ktsFbWWVmVncNLICeP+lgBse6XpZLz+IcMPeK+fV22XrpkwGMa7/FdJlYmpjzca/PZTnUIbvCw/RIq35QZSua8gHgm462WzAjL3qFbLyXwua6pa46MpXHHeUTTQ/sdkREIPhycCcJjjts+I0Vpx146CM7zTKXk+9MrNddHbP+bP5me8E611XNCospfm0Fu5f2eNsDPYmx+RoHqVWSatsVo9FOrBiyJRT0kYR043S4CezampOa3tcY8ZGtx7r0Y2l2x6uj/HlgoLNTivmYakU6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
